In [ ]:
2) Write a program

In [3]:
judith=np.array([[[2,3,4],[1,3,5]],[[5,6,7],[8,9,10]]])
print(judith[0])
print(type(judith))

[[2 3 4]
 [1 3 5]]
<class 'numpy.ndarray'>


In [2]:
# reversal

import numpy as np

arr = np.array([16, 17, 18, 19, 20])

print(arr[::-1])

[20 19 18 17 16]


In [4]:
# jump of 3
arr = np.array([20, 19, 18, 17, 16])

print(arr[::-3])

[16 19]


In [6]:
arr = np.array([1, 2, 3, 4], ndmin=7) 

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[1 2 3 4]]]]]]]
number of dimensions : 7


In [ ]:
5) Slice "12" in [[[2,3,4],[5,6,7]],[[8,9,10],[11,12,13]]]

In [7]:
import numpy as np

arr = np.array([[[2,3,4],[5,6,7]],[[8,9,10],[11,12,13]]])

print(arr[1,1,1])

12
